apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
      name: mysql
  selector:
    app: {{ .Release.Name }}-mysql
